apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: front-end
  template: 
    metadata:
      labels:  
        app: front-end
    spec:
      containers:
        - name: wisecowimage
          image: pavithra123456789/wisecow:200
          ports:
           - containerPort: 4499 