name: Build and Push Wisecow Docker Image

on:
  push:
    branches:
      - main   # runs only on main branch pushes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./wisecow-CICD               # root of repo where Dockerfile is
          file: ./wisecow-CICD/Dockerfile        # adjust if Dockerfile in subfolder
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/wisecow:${{ github.run_number }}

      - name: Logout from Docker
        run: docker logout
